'use client'
import { Inter } from 'next/font/google'

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import BasicAppBar from './basicAppBar';
import Footer from '../components/footer/footer';

import { ThemeProvider } from '@mui/material/styles';
import { muiTheme } from './muiTheme';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
 		<body style={{margin: 0}}>
			<ThemeProvider theme={muiTheme}>
				<BasicAppBar/>
				{children}
        <Footer/>
			</ThemeProvider>
		</body>
    </html>
  )
}
